# Generated by Django 3.2.2 on 2021-05-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('energy', models.FloatField()),
                ('reactive_energy', models.FloatField()),
                ('power', models.FloatField()),
                ('maximeter', models.FloatField()),
                ('reactive_power', models.FloatField()),
                ('voltage', models.FloatField()),
                ('intensity', models.FloatField()),
                ('power_factor', models.FloatField()),
            ],
            options={
                'db_table': 'electricity_consumption',
                'managed': False,
            },
        ),
    ]
