# Generated by Django 3.2.2 on 2021-05-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_electricityconsumption_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricityconsumption',
            options={'managed': False},
        ),
    ]
